apiVersion: v1
kind: Service
metadata:
  name: load-balancer
spec:
  selector:
    app: website-categorizer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  clusterIP: 10.96.0.100
  type: LoadBalancer